steps:
# Build the build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'docker-make', 'build']

# Build the k8s config
- name: 'docker-make'
  args: ['kustomization.yaml']

# Publish images
- name: 'docker-make'
  args: ['docker_push']

# Deploy to k8s cluster
- name: 'docker-make'
  entrypoint: "bash"
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials --zone us-central1-a wandering-frog
      KUBECTX="gke_worldpeaceio-production_us-central1-a_wandering-frog" make deploy

# Options
timeout: 300s
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/${REPO_NAME}/${BRANCH_NAME}/${SHORT_SHA}-${BUILD_ID}'
    paths: ['artifacts/wordpress-integration-services.yaml']
