steps:
# Build the build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'docker-make', 'build']

# Build the docker images and the k8s artifact, push the images
- name: 'docker-make'
  args: ['build', 'docker_push']
  env:
  - 'IMAGE_REGISTRY=us.gcr.io/${PROJECT_ID}/'

# Deploy to k8s cluster
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=artifacts/wordpress-integration-services.yaml
  - --location=us-central1-a
  - --cluster=gaia
  - --namespace=default

# Options
timeout: 300s
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/${REPO_NAME}/${BRANCH_NAME}/${SHORT_SHA}-${BUILD_ID}'
    paths: ['artifacts/wordpress-integration-services.yaml']
