apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wordpress-integration-update-develop
  labels:
    app: wordpress-integration-services
spec:
  schedule: "24 */3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wordpress-integration-services
            image: us.gcr.io/worldpeace-container-registry/wordpress-integration-services
            args: ["update_develop/main.py"]
            volumeMounts:
            - name: "secrets"
              mountPath: "/secrets"
              readOnly: true
          volumes:
          - name: secrets
            secret:
              secretName: github-app-key-pem
          restartPolicy: Never
