apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wordpress-integration-merge-master
  labels:
    app: wordpress-integration-services
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wordpress-integration-services
            image: us.gcr.io/worldpeace-container-registry/wordpress-integration-services
            command: ["python"]
            args: ["/app/merge_master/main.py"]
            volumeMounts:
            - name: "secrets"
              mountPath: "/secrets"
              readOnly: true
          volumes:
          - name: secrets
            secret:
              secretName: github-app-key-pem
          restartPolicy: OnFailure
